// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akcorcehvpmmaobbkfet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrY29yY2VodnBtbWFvYmJrZmV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTU2OTIsImV4cCI6MjA1OTg5MTY5Mn0.5Kd4oDF4Xc2G-5HfnxkJMKZBhWuk8XN26FFe0YLzWYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);